export interface PartDataModel {
    id: number,
    partNumber?: string,
    partName?: string,
    description?: string,
    partSize?: string,
    remarks?: string,
    partPrice?: string,
    status?: string,
    extraAttr1: null,
    extraAttr2: null,
    extraAttr3: null,
    extraAttr4: null,
    extraAttr5: null,
    extraAttr6: null,
    extraAttr7: null,
    extraAttr8: null,
    extraAttr9: null,
    extraAttr10: null,
    createdBy: string,
    createdOn: string,
    modifiedBy: string,
    modifiedOn: string,
    messageStatus: null
}