export interface PlantDataModel {
    id: number,
    plantCode: string,
    locationId: string,
    plantDesc: string,
    plantAddress: string,
    city: string,
    stateCode: string,
    countryCode: string,
    postalCode: string,
    panNo: string,
    gstnNo: string,
    auCode: string,
    plantType: string,
    siteCode: string,
    dsc: string,
    dcp: string,
    transactionType: string,
    status: string,
    extraAttr1: string,
    extraAttr2: string,
    extraAttr3: string,
    extraAttr4: string,
    extraAttr5: string,
    extraAttr6: string,
    extraAttr7: string,
    extraAttr8: string,
    extraAttr9: string,
    extraAttr10: string,
    createdBy: string,
    createdOn: string,
    modifiedBy: string,
    modifiedOn: string,
    messageStatus: null,
    transactionTypeMapping: [
        {
            id: number,
            status: string,
            attribute1: null,
            attribute2: null,
            attribute3: null,
            attribute4: null,
            txnTypeId: null,
            name: string,
            code: string
        }
    ]
}