export interface PointChargeDataModel {
  id: number,
  locationId: string,
  pointName: string,
  pointCharge: string,
  sameLocationCharge: string,
  status: string,
  extraAttr1: string,
  extraAttr2: string,
  extraAttr3: string,
  extraAttr4: string,
  extraAttr5: string,
  extraAttr6: string,
  extraAttr7: string,
  extraAttr8: string,
  extraAttr9: string,
  extraAttr10: string,
  createdBy: string,
  createdOn: string,
  modifiedBy: string,
  modifiedOn: string,
  approvedByMaterial: string,
  approvedByMaterialOn: string,
  approvedByAccounts: string,
  approvedByAccountsOn: string,
  messageStatus: string
}
