export interface VehicleDataModel {
    id: number;
    locationId: number;
    vehicleNumber: string;
    vehicleSize: number;
    transporterId: number;
    vehicleCondition: string;
    transporterEntity: {
      locationId: number,
      transporterCode: string,
      transporterName: string,
      transporterAddress1: string,
      transporterAddress2: string,
      city: string,
      stateCode: string,
      countryCode: string,
      postalCode: string,
      panNo: string,
      gstnNo: string,
      transporterPayterm: string,
      transporterPaytermStatus: string,
      transporterContactNo: string,
      transporterMailId: string,
      gstType: string,
      regdDetails: string,
      autoBiltiRequiredFlag: string,
      autoBiltiStartingCharacter: string,
      consignorName: string,
      consignorContactInformation: string,
      biltiHeaderComments: string,
      note: string,
      footer: string,
      inactiveDate: string,
      transporterStatus: string,
      createdBy:string,
      createdOn: string,
      modifiedBy: string,
      modifiedOn: string,
      messageStatus: string
    },
    remarks: string;
    vehicleStatus: string;
    inactiveDate: string;
    attribute1: string;
    attribute2: string;
    attribute3: string;
    attribute4: string;
    attribute5: string;
    attribute6: string;
    attribute7: string;
    attribute8: string;
    attribute9: string;
    attribute10: string;
    createdBy: string;
    createdOn: string;
    modifiedBy: string;
    modifiedOn: string;
    messageStatus: string;
  }
  
